[map]
map_name = 'Town10HD_Opt'
map_path = 'Carla/Maps/'
draw_obstacles = false
sumo_coordinates = false
spectator_location = [-47.0, 21.0, 20]
spectator_rotation = [-90.0, 0.0, 0.0]

[walker]
pedestrian_seed = 2020
#spectator_focus = 'ped_4'
draw_bounding_boxes = false
ai_controller = false

[[walker.pedestrians]]
role_name = 'ped_0'
spawn_location = [-37.0, 21.0, 1.0]
spawn_rotation = [0.0, 180.0, 0.0]
destination = [-57.0, 21.0, 0.0]
spawn_speed = 1.1

[[walker.pedestrians]]
role_name = 'ped_1'
spawn_location = [-37.49, 24.09, 1.0]
spawn_rotation = [0.0, 180.0, 0.0]
destination = [-56.51, 17.91, 0.0]
spawn_speed = 1.0

[[walker.pedestrians]]
role_name = 'ped_2'
spawn_location = [-38.91, 26.88, 1.0]
spawn_rotation = [0.0, 180.0, 0.0]
destination = [-55.09, 15.12, 0.0]
spawn_speed = 1.2

[[walker.pedestrians]]
role_name = 'ped_3'
spawn_location = [-41.12, 29.09, 1.0]
spawn_rotation = [0.0, 180.0, 0.0]
destination = [-52.88, 12.91, 0.0]
spawn_speed = 0.9

[[walker.pedestrians]]
role_name = 'ped_4'
spawn_location = [-43.91, 30.51, 1.0]
spawn_rotation = [0.0, 180.0, 0.0]
destination = [-50.09, 11.49, 0.0]
spawn_speed = 1.0

[[walker.pedestrians]]
role_name = 'ped_5'
spawn_location = [-47.0, 31.0, 1.0]
spawn_rotation = [0.0, 180.0, 0.0]
destination = [-47.0, 11.0, 0.0]
spawn_speed = 0.8

[[walker.pedestrians]]
role_name = 'ped_6'
spawn_location = [-50.09, 30.51, 1.0]
spawn_rotation = [0.0, 180.0, 0.0]
destination = [-43.91, 11.49, 0.0]
spawn_speed = 1.1

[[walker.pedestrians]]
role_name = 'ped_7'
spawn_location = [-52.88, 29.09, 1.0]
spawn_rotation = [0.0, 180.0, 0.0]
destination = [-41.12, 12.91, 0.0]
spawn_speed = 1.0

[[walker.pedestrians]]
role_name = 'ped_8'
spawn_location = [-55.09, 26.88, 1.0]
spawn_rotation = [0.0, 180.0, 0.0]
destination = [-38.91, 15.12, 0.0]
spawn_speed = 1.2

[[walker.pedestrians]]
role_name = 'ped_9'
spawn_location = [-56.51, 24.09, 1.0]
spawn_rotation = [0.0, 180.0, 0.0]
destination = [-37.49, 17.91, 0.0]
spawn_speed = 0.9

[[walker.pedestrians]]
role_name = 'ped_10'
spawn_location = [-57.0, 21.0, 1.0]
spawn_rotation = [0.0, 0.0, 0.0]
destination = [-37.0, 21.0, 0.0]
spawn_speed = 1.0

[[walker.pedestrians]]
role_name = 'ped_11'
spawn_location = [-56.51, 17.91, 1.0]
spawn_rotation = [0.0, 0.0, 0.0]
destination = [-37.49, 24.09, 0.0]
spawn_speed = 1.2

[[walker.pedestrians]]
role_name = 'ped_12'
spawn_location = [-55.09, 15.12, 1.0]
spawn_rotation = [0.0, 0.0, 0.0]
destination = [-38.91, 26.88, 0.0]
spawn_speed = 1.1

[[walker.pedestrians]]
role_name = 'ped_13'
spawn_location = [-52.88, 12.91, 1.0]
spawn_rotation = [0.0, 0.0, 0.0]
destination = [-41.12, 29.09, 0.0]
spawn_speed = 1.0

[[walker.pedestrians]]
role_name = 'ped_14'
spawn_location = [-50.09, 11.49, 1.0]
spawn_rotation = [0.0, 0.0, 0.0]
destination = [-43.91, 30.51, 0.0]
spawn_speed = 0.9

[[walker.pedestrians]]
role_name = 'ped_15'
spawn_location = [-47.0, 11.0, 1.0]
spawn_rotation = [0.0, 0.0, 0.0]
destination = [-47.0, 31.0, 0.0]
spawn_speed = 1.1

[[walker.pedestrians]]
role_name = 'ped_16'
spawn_location = [-43.91, 11.49, 1.0]
spawn_rotation = [0.0, 0.0, 0.0]
destination = [-50.09, 30.51, 0.0]
spawn_speed = 1.2

[[walker.pedestrians]]
role_name = 'ped_17'
spawn_location = [-41.12, 12.91, 1.0]
spawn_rotation = [0.0, 0.0, 0.0]
destination = [-52.88, 29.09, 0.0]
spawn_speed = 1.0

[[walker.pedestrians]]
role_name = 'ped_18'
spawn_location = [-38.91, 15.12, 1.0]
spawn_rotation = [0.0, 0.0, 0.0]
destination = [-55.09, 26.88, 0.0]
spawn_speed = 0.8

[[walker.pedestrians]]
role_name = 'ped_19'
spawn_location = [-37.49, 17.91, 1.0]
spawn_rotation = [0.0, 0.0, 0.0]
destination = [-56.51, 24.09, 0.0]
spawn_speed = 1.1
