[map]
map_name = 'Town10HD_Opt'
map_path = 'Carla/Maps/'
draw_obstacles = true
sumo_coordinates = false
spectator_location = [-54.0, 28.0, 20]
spectator_rotation = [-90.0, 0.0, 0.0]

[walker]
pedestrian_seed = 2015
despawn_on_arrival = true
despawn_threshold = 0.2
#spectator_focus = 'ped_4'
draw_bounding_boxes = false
ai_controller = false

[[walker.ped_spawner]]
spawn_location = [-52.3, 45.6, 1.0]
waypoints = [-52.3, 0.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-51.0, 44.0, 1.0]
waypoints = [-51.0, 0.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-53.0, 44.0, 1.0]
waypoints = [-53.0, 0.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-51.3, 46.5, 1.0]
waypoints = [-51.3, 0.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-52.0, 47.0, 1.0]
waypoints = [-52.0, 0.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-53.1, 46.7, 1.0]
waypoints = [-53.1, 0.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-51.0, 48.5, 1.0]
waypoints = [-51.0, 0.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-52.0, 49.0, 1.0]
waypoints = [-52.0, 0.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-53.0, 48.0, 1.0]
waypoints = [-53.0, 0.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-51.0, 50.0, 1.0]
waypoints = [-51.0, 0.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-73.0, 29.0, 1.0]
waypoints = [-25.0, 29.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-73.0, 28.0, 1.0]
waypoints = [-25.0, 28.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-72.0, 27.0, 1.0]
waypoints = [-25.0, 27.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-72.0, 29.5, 1.0]
waypoints = [-25.0, 29.5, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-68.0, 27.3, 1.0]
waypoints = [-25.0, 27.3, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-69.5, 29.3, 1.0]
waypoints = [-25.0, 29.3, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-69.0, 28.0, 1.0]
waypoints = [-25.0, 28.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-70.0, 26.5, 1.0]
waypoints = [-25.0, 26.5, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-70.0, 29.0, 1.0]
waypoints = [-25.0, 29.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [-70.9, 27.9, 1.0]
waypoints = [-25.0, 27.9, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[obstacles]
resolution = 0.1

# lane 1
[[obstacles.borders]]
start_point = [-53.9, 59.8]
end_point = [-53.9, 29.8]

[[obstacles.borders]]
start_point = [-53.9, 26.3]
end_point = [-53.9, -6.3]

[[obstacles.borders]]
start_point = [-50.4, 59.8]
end_point = [-50.4, 29.8]

[[obstacles.borders]]
start_point = [-50.4, 26.3]
end_point = [-50.4, -6.3]

#lane 2
[[obstacles.borders]]
start_point = [-83.9, 29.8]
end_point = [-53.9, 29.8]

[[obstacles.borders]]
start_point = [-50.4, 29.8]
end_point = [-20.4, 29.8]

[[obstacles.borders]]
start_point = [-83.9, 26.3]
end_point = [-53.9, 26.3]

[[obstacles.borders]]
start_point = [-50.4, 26.3]
end_point = [-20.4, 26.3]