[map]
map_name = 'Town01_Opt'
map_path = 'Carla/Maps/'
draw_obstacles = false
sumo_coordinates = true
sumo_offset = [0.06, 328.61, 0.0]

[walker]
pedestrian_seed = 2020
despawn_on_arrival = true
waypoint_threshold = 1.0
draw_bounding_boxes = false
ai_controller = true
spectator_focus = 'ped_0'

[[walker.ped_spawner]]
spawn_location = [109.0, 269.0, 0.3]
destination = [129.0, 269.0, 0.0]
speed = 0.5
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [118.0, 269.0, 0.3]
destination = [100.0, 269.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[obstacles]
resolution = 0.1

#[[obstacles.borders]]
#start_point = [116.0, 270.0]
#end_point = [117.0, 268.5]