[map]
map_name = 'Town10HD_Opt'
map_path = 'Carla/Maps/'
draw_obstacles = false
sumo_coordinates = false
unload_props = false
spectator_location = [115.0, 62.0, 29.0]
spectator_rotation = [-70.0, 180.0, 0.0]

[walker]
pedestrian_seed = 2021
despawn_on_arrival = true
waypoint_threshold = 2
waypoint_distance = 5
jaywalking_weight = 2
draw_bounding_boxes = false
ai_controller = false

[[walker.ped_spawner]]
spawn_location = [92.0, 91.0, 1.0]
generate_route = 'JAYWALKING'
destination = [118.0, 67.0, 0.0]
speed = 1.0
quantity = 1
spawn_time = 0.0

[obstacles]
resolution = 0.5