[map]
map_name = 'Town01_Opt'
map_path = 'Carla/Maps/'
draw_obstacles = false
spectator_location = [234.0, 5.0, 10]
spectator_rotation = [-40.0, -90.0, 0.0]

[walker]
pedestrian_seed = 2000
despawn_on_arrival = true
waypoint_threshold = 2
variate_speed = 0.3
draw_bounding_boxes = false

[[walker.ped_spawner]]
spawn_location = [244.0, -6.0, 0.0]
destination = [215.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [245.0, -7.0, 0.0]
destination = [215.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [247.0, -5.0, 0.0]
destination = [215.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [243.0, -5.0, 0.0]
destination = [215.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [244.0, -7.0, 0.0]
destination = [215.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [251.0, -5.0, 0.0]
destination = [215.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [249.0, -7.0, 0.0]
destination = [215.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [248.0, -6.0, 0.0]
destination = [215.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

#[[walker.ped_spawner]]
#spawn_location = [247.0, -7.0, 0.0]
#destination = [215.0, -6.0, 0.0]
#speed = 1.2
#quantity = 1
#spawn_time = 0.0
#spawn_interval = 2.0
#
#[[walker.ped_spawner]]
#spawn_location = [248.0, -7.0, 0.0]
#destination = [215.0, -6.0, 0.0]
#speed = 1.2
#quantity = 1
#spawn_time = 0.0
#spawn_interval = 2.0
#
#[[walker.ped_spawner]]
#spawn_location = [220.0, -5.0, 0.0]
#destination = [250.0, -6.0, 0.0]
#speed = 1.2
#quantity = 1
#spawn_time = 0.0
#spawn_interval = 2.0
#
#[[walker.ped_spawner]]
#spawn_location = [221.0, -6.0, 0.0]
#destination = [250.0, -6.0, 0.0]
#speed = 1.2
#quantity = 1
#spawn_time = 0.0
#spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [219.0, -6.5, 0.0]
destination = [250.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [220.0, -7.0, 0.0]
destination = [250.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [221.0, -5, 0.0]
destination = [250.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [224.0, -5.0, 0.0]
destination = [250.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [225.0, -5, 0.0]
destination = [250.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [223.0, -6.5, 0.0]
destination = [250.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [224.0, -7.0, 0.0]
destination = [250.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [225.0, -6.0, 0.0]
destination = [250.0, -6.0, 0.0]
speed = 1.2
quantity = 1
spawn_time = 0.0
spawn_interval = 2.0

[obstacles]
resolution = 0.1

