[map]
map_name = 'Town01_Opt'
map_path = 'Carla/Maps/'
draw_obstacles = false
sumo_coordinates = false
spectator_location = [234.0, 5.0, 10]
spectator_rotation = [-40.0, -90.0, 0.0]

[walker]
pedestrian_seed = 2015
draw_bounding_boxes = false
ai_controller = true

[[walker.ped_spawner]]
spawn_location = [244.0, -6.0, 0.0]
destination = [215.0, -6.0, 0.0]
speed = 1.0
quantity = 20
spawn_time = 0.0
spawn_interval = 2.0

[[walker.ped_spawner]]
spawn_location = [225.0, -6.0, 0.0]
destination = [250.0, -6.0, 0.0]
speed = 1.0
quantity = 20
spawn_time = 0.0
spawn_interval = 2.0

[obstacles]
resolution = 0.1

#[[obstacles.borders]]
#start_point = [250.0, -7.6]
#end_point = [200.0, -7.6]
#
#[[obstacles.borders]]
#start_point = [250.0, -4.0]
#end_point = [200.0, -4.0]
