[map]
map_name = 'Town10HD_Opt'
map_path = 'Carla/Maps/'
draw_obstacles = false
unload_props = false
spectator_location = [-120.3, -17.0, 10.0]
spectator_rotation = [-50.0, 0.0, 0.0]

[walker]
pedestrian_seed = 2020
despawn_on_arrival = true
waypoint_threshold = 2
waypoint_distance = 5
jaywalking_weight = 1
draw_bounding_boxes = false
ai_controller = true

[[walker.ped_spawner]]
spawn_location = [-122.5, -12.0, 1.0]
generate_route = 'JAYWALKING'
destination = [-93.1, -17.0, 0.0]
blueprint = 'walker.pedestrian.0002'
speed = 1.5
quantity = 3
spawn_time = 0.0
spawn_interval = 2.8
crossing_speed_factor = 1.5
crossing_safety_margin = 1.5

#[[walker.ped_spawner]]
#spawn_location = [-122.0, -13.0, 1.0]
#generate_route = 'JAYWALKING'
#destination = [-93.1, -17.0, 0.0]
#speed = 1.5
#quantity = 3
#spawn_time = 0.0
#spawn_interval = 2.1

#[[walker.ped_spawner]]
#spawn_location = [-122.0, -14.0, 1.0]
#generate_route = 'JAYWALKING'
#destination = [-93.1, -17.0, 0.0]
#speed = 1.5
#quantity = 3
#spawn_time = 0.0
#spawn_interval = 2.5
#
#[[walker.ped_spawner]]
#spawn_location = [-93.1, -17.0, 1.0]
#generate_route = 'JAYWALKING'
#destination = [-122.5, -17.0, 1.0]
#speed = 1.5
#quantity = 3
#spawn_time = 0.0
#spawn_interval = 2.8
#
#[[walker.ped_spawner]]
#spawn_location = [-93.5, -18.0, 1.0]
#generate_route = 'JAYWALKING'
#destination = [-122.0, -18.0, 1.0]
#speed = 1.5
#quantity = 3
#spawn_time = 0.0
#spawn_interval = 2.1
#
#[[walker.ped_spawner]]
#spawn_location = [-93.1, -19.0, 1.0]
#generate_route = 'JAYWALKING'
#destination = [-122.0, -19.0, 1.0]
#speed = 1.5
#quantity = 3
#spawn_time = 0.0
#spawn_interval = 2.5
#
[vehicle]
vehicle_seed = 100
variate_speed_factor = 3

[[vehicle.vehicle_spawner]]
spawn_point = 100
blueprint = 'vehicle.tesla.model3'
speed_reduction_factor = 0
auto_pilot = true
quantity = 1
spawn_time = 0.0
spawn_interval = 5.0
ignore_walkers_percentage = 100
ignore_lights_percentage = 100

[[vehicle.vehicle_spawner]]
spawn_point = 12
speed_reduction_factor = 0
auto_pilot = true
quantity = 1
spawn_time = 0.0
spawn_interval = 5.0
ignore_walkers_percentage = 100
ignore_lights_percentage = 100

[obstacles]
resolution = 0.1
ellipse_shape = true
max_obstacle_z_pos = 0.3
