max_speed_multiplier = 1.3
use_ped_radius = false

[forces]
acceleration_force = true
pedestrian_force = true
border_force = true
static_obstacle_force = true
dynamic_obstacle_force = true

[acceleration_force]
tau = 0.5

[pedestrian_force]
lambda = 2.0 # 2.0 +- 0.3
A = 4.5 # 4.5 +- 0.3
gamma = 0.35 # 0.35 +- 0.01
n = 2.0 # 2.0 +- 0.1
n_prime = 3.0 # 3.0 +- 0.7
epsilon = 0.005

[border_force]
a = 6.0
b = 0.3

[static_obstacle_force]
lambda = 2.3
A = 15
gamma = 0.4
n = 2.1
n_prime = 3.0
epsilon = 0.005
perception_threshold = 20

[dynamic_obstacle_force]
lambda = 2.0
A = 50
gamma = 0.4
n = 1.0
n_prime = 3.0
epsilon = 0.005
perception_threshold = 50