max_speed_multiplier = 1.3
use_ped_radius = false

[forces]
goal_attractive_force = true
pedestrian_force = true
obstacle_force = true
ped_repulsive_force = false
space_repulsive_force = false

[field_of_view]
two_phi = 200
out_of_view_factor = 0.5

[ped_ped_potential]
v0 = 2.1
sigma = 0.5
grad_delta = 1e-3

[ped_space_potential]
u0 = 10.0
r = 0.2
grad_delta=1e-3

[pedestrian_force]
lambda = 2.0 # 2.0 +- 0.3
A = 4.5 # 4.5 +- 0.3
gamma = 0.35 # 0.35 +- 0.01
n = 2.0 # 2.0 +- 0.1
n_prime = 3.0 # 3.0 +- 0.7
epsilon = 0.005

[obstacle_force]
a = 4.0
b = 0.1